//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CONSULTA
{
    public int ID { get; set; }
    public Nullable<System.DateTime> FECHA { get; set; }
    public Nullable<int> ID_HOSPITAL { get; set; }
    public Nullable<int> ID_DOCTOR { get; set; }
    public Nullable<int> ID_PACIENTE { get; set; }
    public Nullable<int> ID_RECETA { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    public virtual DOCTOR DOCTOR { get; set; }
    public virtual HOSPITAL HOSPITAL { get; set; }
    public virtual PACIENTE PACIENTE { get; set; }
    public virtual RECETA RECETA { get; set; }
}

public partial class DETALLE_RECETA
{
    public int ID { get; set; }
    public Nullable<int> ID_RECETA { get; set; }
    public Nullable<int> ID_MEDICAMENTO { get; set; }
    public Nullable<int> CANTIDAD { get; set; }
    public string DESCRIPCION { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    public virtual MEDICAMENTO MEDICAMENTO { get; set; }
    public virtual RECETA RECETA { get; set; }
}

public partial class DOCTOR
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DOCTOR()
    {
        this.CONSULTA = new HashSet<CONSULTA>();
        this.DOCTOR_ESPECIALIDAD = new HashSet<DOCTOR_ESPECIALIDAD>();
        this.HOSPITAL_DOCTOR = new HashSet<HOSPITAL_DOCTOR>();
        this.VISITA = new HashSet<VISITA>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public string CEDULA { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    public string SEXO { get; set; }
    public string DIRECCION { get; set; }
    public string TELEFONO { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CONSULTA> CONSULTA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DOCTOR_ESPECIALIDAD> DOCTOR_ESPECIALIDAD { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HOSPITAL_DOCTOR> HOSPITAL_DOCTOR { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VISITA> VISITA { get; set; }
}

public partial class DOCTOR_ESPECIALIDAD
{
    public int ID { get; set; }
    public Nullable<int> ID_DOCTOR { get; set; }
    public Nullable<int> ID_ESPECIALIDAD { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    public virtual DOCTOR DOCTOR { get; set; }
    public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
}

public partial class ESPECIALIDAD
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ESPECIALIDAD()
    {
        this.DOCTOR_ESPECIALIDAD = new HashSet<DOCTOR_ESPECIALIDAD>();
        this.HOSPITAL_ESPECIALIDAD = new HashSet<HOSPITAL_ESPECIALIDAD>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DOCTOR_ESPECIALIDAD> DOCTOR_ESPECIALIDAD { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HOSPITAL_ESPECIALIDAD> HOSPITAL_ESPECIALIDAD { get; set; }
}

public partial class HOSPITAL
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HOSPITAL()
    {
        this.CONSULTA = new HashSet<CONSULTA>();
        this.HOSPITAL_ESPECIALIDAD = new HashSet<HOSPITAL_ESPECIALIDAD>();
        this.HOSPITAL_DOCTOR = new HashSet<HOSPITAL_DOCTOR>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string DIRECCION { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CONSULTA> CONSULTA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HOSPITAL_ESPECIALIDAD> HOSPITAL_ESPECIALIDAD { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HOSPITAL_DOCTOR> HOSPITAL_DOCTOR { get; set; }
}

public partial class HOSPITAL_DOCTOR
{
    public int ID { get; set; }
    public Nullable<int> ID_HOSPITAL { get; set; }
    public Nullable<int> ID_DOCTOR { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    public virtual DOCTOR DOCTOR { get; set; }
    public virtual HOSPITAL HOSPITAL { get; set; }
}

public partial class HOSPITAL_ESPECIALIDAD
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HOSPITAL_ESPECIALIDAD()
    {
        this.INTERNADO = new HashSet<INTERNADO>();
    }

    public int ID { get; set; }
    public Nullable<int> CUARTOS { get; set; }
    public Nullable<int> CUARTOS_LIBRES { get; set; }
    public Nullable<int> PISO { get; set; }
    public Nullable<int> ID_HOSPITAL { get; set; }
    public Nullable<int> ID_ESPECIALIDAD { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
    public virtual HOSPITAL HOSPITAL { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<INTERNADO> INTERNADO { get; set; }
}

public partial class INTERNADO
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public INTERNADO()
    {
        this.VISITA = new HashSet<VISITA>();
    }

    public int ID { get; set; }
    public Nullable<System.DateTime> INGRESO { get; set; }
    public Nullable<System.DateTime> SALIDA { get; set; }
    public Nullable<int> ID_PACIENTE { get; set; }
    public Nullable<int> ID_HOSPITAL_ESPECIALIDAD { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    public virtual HOSPITAL_ESPECIALIDAD HOSPITAL_ESPECIALIDAD { get; set; }
    public virtual PACIENTE PACIENTE { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VISITA> VISITA { get; set; }
}

public partial class MEDICAMENTO
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MEDICAMENTO()
    {
        this.DETALLE_RECETA = new HashSet<DETALLE_RECETA>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string INGREDIENTE_ACTIVO { get; set; }
    public Nullable<int> PIEZAS { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DETALLE_RECETA> DETALLE_RECETA { get; set; }
}

public partial class PACIENTE
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PACIENTE()
    {
        this.CONSULTA = new HashSet<CONSULTA>();
        this.INTERNADO = new HashSet<INTERNADO>();
    }

    public int ID { get; set; }
    public string NOMBRE { get; set; }
    public string APELLIDO { get; set; }
    public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
    public string SEXO { get; set; }
    public string DIRECCION { get; set; }
    public string TELEFONO { get; set; }
    public string CORREO_ELECTRONICO { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CONSULTA> CONSULTA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<INTERNADO> INTERNADO { get; set; }
}

public partial class RECETA
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RECETA()
    {
        this.CONSULTA = new HashSet<CONSULTA>();
        this.DETALLE_RECETA = new HashSet<DETALLE_RECETA>();
        this.VISITA = new HashSet<VISITA>();
    }

    public int ID { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CONSULTA> CONSULTA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DETALLE_RECETA> DETALLE_RECETA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<VISITA> VISITA { get; set; }
}

public partial class VISITA
{
    public int ID { get; set; }
    public Nullable<System.DateTime> FECHA { get; set; }
    public Nullable<int> ID_DOCTOR { get; set; }
    public Nullable<int> ID_INTERNADO { get; set; }
    public Nullable<int> ID_RECETA { get; set; }
    public Nullable<bool> VISIBLE { get; set; }

    public virtual DOCTOR DOCTOR { get; set; }
    public virtual INTERNADO INTERNADO { get; set; }
    public virtual RECETA RECETA { get; set; }
}
