//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_RECETA
    {
        public int ID { get; set; }
        public Nullable<int> ID_RECETA { get; set; }
        public Nullable<int> ID_MEDICAMENTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<bool> VISIBLE { get; set; }
    }
}
