//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTERNADO()
        {
            this.VISITA = new HashSet<VISITA>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> INGRESO { get; set; }
        public Nullable<System.DateTime> SALIDA { get; set; }
        public Nullable<int> ID_PACIENTE { get; set; }
        public Nullable<int> ID_HOSPITAL_ESPECIALIDAD { get; set; }
        public Nullable<bool> VISIBLE { get; set; }
    
        public virtual HOSPITAL_ESPECIALIDAD HOSPITAL_ESPECIALIDAD { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISITA> VISITA { get; set; }
    }
}
